version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    groups:
      website-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    groups:
      ui-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /design-tokens
    schedule:
      interval: weekly
    groups:
      design-tokens-deps:
        patterns: ["*"]
