#ifndef SC_ERROR_H
#define SC_ERROR_H

typedef enum sc_error {
    SC_OK = 0,

    SC_ERR_OUT_OF_MEMORY,
    SC_ERR_INVALID_ARGUMENT,
    SC_ERR_NOT_FOUND,
    SC_ERR_ALREADY_EXISTS,
    SC_ERR_NOT_SUPPORTED,
    SC_ERR_PERMISSION_DENIED,
    SC_ERR_TIMEOUT,
    SC_ERR_IO,
    SC_ERR_PARSE,

    SC_ERR_CONFIG_INVALID,
    SC_ERR_CONFIG_NOT_FOUND,

    SC_ERR_PROVIDER_UNAVAILABLE,
    SC_ERR_PROVIDER_AUTH,
    SC_ERR_PROVIDER_RATE_LIMITED,
    SC_ERR_PROVIDER_RESPONSE,

    SC_ERR_CHANNEL_SEND,
    SC_ERR_CHANNEL_START,
    SC_ERR_CHANNEL_NOT_CONFIGURED,

    SC_ERR_TOOL_EXECUTION,
    SC_ERR_TOOL_VALIDATION,
    SC_ERR_TOOL_NOT_FOUND,

    SC_ERR_MEMORY_STORE,
    SC_ERR_MEMORY_RECALL,
    SC_ERR_MEMORY_BACKEND,

    SC_ERR_SECURITY_COMMAND_NOT_ALLOWED,
    SC_ERR_SECURITY_HIGH_RISK_BLOCKED,
    SC_ERR_SECURITY_APPROVAL_REQUIRED,
    SC_ERR_SECURITY_RATE_LIMITED,
    SC_ERR_SECURITY_LOCKOUT,

    SC_ERR_PERIPHERAL_NOT_CONNECTED,
    SC_ERR_PERIPHERAL_IO,
    SC_ERR_PERIPHERAL_FLASH_FAILED,
    SC_ERR_PERIPHERAL_DEVICE_NOT_FOUND,

    SC_ERR_TUNNEL_START_FAILED,
    SC_ERR_TUNNEL_URL_NOT_FOUND,

    SC_ERR_GATEWAY_RATE_LIMITED,
    SC_ERR_GATEWAY_BODY_TOO_LARGE,
    SC_ERR_GATEWAY_AUTH,

    SC_ERR_CRYPTO_ENCRYPT,
    SC_ERR_CRYPTO_DECRYPT,
    SC_ERR_CRYPTO_HMAC,

    SC_ERR_JSON_PARSE,
    SC_ERR_JSON_TYPE,
    SC_ERR_JSON_DEPTH,

    SC_ERR_INTERNAL,
    SC_ERR_SUBAGENT_TOO_MANY,

    SC_ERR_COUNT
} sc_error_t;

const char *sc_error_string(sc_error_t err);

#endif
